---

- hosts: server1
  become: yes

  handlers:
    - name: print facts
      debug:
        msg: "{{ ansible_facts }}"

  tasks:

    - name: Create Directory
      file:
        path: "/home/centos/brki_test"
        state: directory
        mode: '0755'
      notify: print facts
