---

- hosts: mitogen-test01
  become: yes
  tasks:

    - name: Install httpd service
      yum:
        name: httpd
        state: present

    - name: Start httpd service
      service:
         name: httpd
         state: started